import fs from 'fs/promises';
import path from 'path';
import { z } from 'zod';

/**
 * Self-Skill Making: Allows Marie to create new capabilities dynamically.
 */
export default {
  name: 'make_skill',
  description: 'Create a new dynamic skill for Marie. Provide the name, description, parameters schema (OpenAI format), and JS logic.',
  schema: z.object({
    name: z.string().regex(/^[a-z_]+$/).max(30).describe('Lowercase name with underscores (e.g., weather_checker)'),
    description: z.string().describe('Clear description of what the tool does'),
    parameters: z.object({
        type: z.literal('object'),
        properties: z.record(z.any()),
        required: z.array(z.string())
    }).describe('OpenAI-compatible JSON schema for input parameters'),
    logic: z.string().describe('The JavaScript code for the handler function body. deps are pre-imported: fetch, z (zod).')
  }),
  parameters: {
    type: 'object',
    properties: {
      name: { type: 'string', pattern: '^[a-z_]+$', maxLength: 30 },
      description: { type: 'string' },
      parameters: { 
          type: 'object',
          properties: {
              type: { type: 'string', enum: ['object'] },
              properties: { type: 'object' },
              required: { type: 'array', items: { type: 'string' } }
          },
          required: ['type', 'properties', 'required']
      },
      logic: { type: 'string', description: 'JavaScript code for the handler. use async if needed.' }
    },
    required: ['name', 'description', 'parameters', 'logic']
  },
  handler: async ({ name, description, parameters, logic }: any, context: any) => {
    const dynamicDir = path.join(process.cwd(), 'marie-skills', 'tools', 'dynamic');
    const filePath = path.join(dynamicDir, `${name}.js`);

    // 1. Security Scan
    const forbidden = ['process.exit', 'child_process', 'exec(', 'rm ', 'unlink', 'import ', 'require('];
    for (const word of forbidden) {
      if (logic.includes(word)) {
        return { success: false, error: `Security Violation: Forbidden keyword "${word}" found in logic.` };
      }
    }

    // 2. Generate File Content
    const fileContent = `
/**
 * Auto-generated by Marie on ${new Date().toISOString()}
 */
import { z } from 'zod';
import { fetch } from 'undici';

export default {
  name: '${name}',
  description: '${description.replace(/'/g, "\\'")}',
  parameters: ${JSON.stringify(parameters, null, 2)},
  handler: async (params, context) => {
    try {
      ${logic}
    } catch (error) {
      return { success: false, error: error.message };
    }
  }
};
`;

    try {
      await fs.writeFile(filePath, fileContent, 'utf-8');
      
      // 3. Hot Reload (if we have access to skills manager via context)
      if (context.skills && typeof context.skills.hotReload === 'function') {
        await context.skills.hotReload(name, filePath);
      }

      return { 
        success: true, 
        message: `Skill "${name}" created and loaded.`,
        path: filePath
      };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }
};
